---

# Install tasks for Debian family
#------------------------------------------------------------------------------

- name: 'INSTALL | APT | Install system prerequisites'
  apt:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_system_prerequisites }}"


- name: 'INSTALL | APT | Manage PostgreSQL GPG keys'
  apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_gpg_keys }}"
  when: 'postgresql_use_upstream | bool'


- name: 'INSTALL | APT | Configure PostgreSQL repositories'
  apt_repository:
    filename: "{{ item.filename | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    repo: "{{ item.repo }}"
    update_cache: True
    state: "{{ item.state | default('present') }}"
  register: 'postgresql_register_repositories'
  with_items: "{{ postgresql_repositories }}"
  when: 'postgresql_use_upstream | bool'


- name: 'INSTALL | APT | Update packages list if repositories not updated'
  apt:
    update_cache: True
    cache_valid_time: "{{ postgresql_cache_valid_time }}"
  when: 'not postgresql_register_repositories | changed'


- name: 'INSTALL | APT | Install PostgreSQL packages'
  apt:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  notify: 'HANDLER | PostgreSQL restart'
  with_items: "{{ postgresql_packages }}"
