---

# Main tasks file for postgresql role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::postgresql'
    - 'role::postgresql::init'
