---

# Main tasks file for postgresql role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::postgresql'
    - 'role::postgresql::init'


- name: 'INSTALL | Manage Postgresql installation tasks'
  include: "{{ role_path }}/tasks/install/{{ ansible_os_family | lower }}_family.yml"
  become: True
  tags:
    - 'role::postgresql'
    - 'role::postgresql::install'


- name: 'INSTALL | Manage Postgresql services tasks'
  include: "{{ role_path }}/tasks/install/manage_services.yml"
  become: True
  tags:
    - 'role::postgresql'
    - 'role::postgresql::install'


- name: 'INSTALL | Manage Postgresql users and groups configuration tasks'
  include: "{{ role_path }}/tasks/install/manage_system_users.yml"
  become: True
  tags:
    - 'role::postgresql'
    - 'role::postgresql::install'


- name: 'CONFIG | Manage Postgresql configuration files tasks'
  include: "{{ role_path }}/tasks/config/manage_config_files.yml"
  become: True
  tags:
    - 'role::postgresql'
    - 'role::postgresql::config'


- name: 'HANDLERS | Force handlers exec  before databases and users management'
  meta: 'flush_handlers'


- name: 'CONFIG | Manage Postgresql databases tasks'
  include: "{{ role_path }}/tasks/config/manage_databases.yml"
  become: True
  tags:
    - 'role::postgresql'
    - 'role::postgresql::config'
    - 'role::postgresql::config::databases'


- name: 'CONFIG | Manage Postgresql databases extensions tasks'
  include: "{{ role_path }}/tasks/config/manage_databases_extensions.yml"
  become: True
  tags:
    - 'role::postgresql'
    - 'role::postgresql::config'
    - 'role::postgresql::config::databases-extensions'


- name: 'CONFIG | Manage Postgresql users tasks'
  include: "{{ role_path }}/tasks/config/manage_users.yml"
  become: True
  tags:
    - 'role::postgresql'
    - 'role::postgresql::config'
    - 'role::postgresql::config::users'


- name: 'CONFIG | Manage Postgresql privileges tasks'
  include: "{{ role_path }}/tasks/config/manage_privileges.yml"
  become: True
  tags:
    - 'role::postgresql'
    - 'role::postgresql::config'
    - 'role::postgresql::config::privileges'
