---

# Main tasks file for postgresql role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::postgresql'
    - 'role::postgresql::init'


- name: 'INSTALL | Manage Postgresql installation tasks'
  include: "{{ role_path }}/tasks/install/{{ ansible_os_family | lower }}_family.yml"
  become: True
  tags:
    - 'role::postgresql'
    - 'role::postgresql::install'


- name: 'INSTALL | Manage Postgresql services tasks'
  include: "{{ role_path }}/tasks/install/manage_services.yml"
  become: True
  tags:
    - 'role::postgresql'
    - 'role::postgresql::install'


- name: 'CONFIG | Manage Postgresql users and groups configuration tasks'
  include: "{{ role_path }}/tasks/config/manage_users.yml"
  become: True
  tags:
    - 'role::postgresql'
    - 'role::postgresql::config'


- name: 'CONFIG | Manage Postgresql configuration files tasks'
  include: "{{ role_path }}/tasks/config/manage_config_files.yml"
  become: True
  tags:
    - 'role::postgresql'
    - 'role::postgresql::config'
