---

# PostgreSQL users and groups tasks
#------------------------------------------------------------------------------

- name: 'CONFIG | Manage PostgreSQL groups'
  group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    gid: "{{ item.gid | default(omit) }}"
  with_items: "{{ postgresql_groups }}"


- name: 'CONFIG | Manage PostgreSQL users'
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    home: "{{ item.home }}"
    shell: "{{ item.shell }}"
    state: "{{ item.state | default('present') }}"
    uid: "{{ item.uid | default(omit) }}"
  with_items: "{{ postgresql_users }}"
