---

# PostgreSQL configuration files management
#------------------------------------------------------------------------------

- name: 'CONFIG | Manage main configuration file'
  template:
    src: "{{ role_path }}/templates/etc/common.conf.j2"
    dest: "{{ postgresql_paths.config_files.main.path }}"
    owner: "{{ postgresql_paths.config_files.main.owner }}"
    group: "{{ postgresql_paths.config_files.main.group }}"
    mode: "{{ postgresql_paths.config_files.main.mode }}"
  notify: 'HANDLER | PostgreSQL restart'
  vars:
    config_items: "{{ postgresql_config_main }}"
