---

- name: 'Ensure PostgreSQL users are present'
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    expires: "{{ item.expires | default(omit) }}"
    db: "{{ item.db | default(omit) }}"
    fail_on_user: "{{ item.fail_on_user | default(omit) }}"
    no_password_changes: "{{ item.no_password_changes | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default(postgresql_system_user.name) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(postgresql_paths.socket.path) }}"
    port: "{{ item.port | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_users }}"
  no_log: True
