---

# PostgreSQL configuration files management
#------------------------------------------------------------------------------

- name: 'CONFIG | Manage environment configuration file'
  template:
    src: "{{ role_path }}/templates/etc/common.conf.j2"
    dest: "{{ postgresql_paths.config_files.environment.path }}"
    owner: "{{ postgresql_paths.config_files.environment.owner }}"
    group: "{{ postgresql_paths.config_files.environment.group }}"
    mode: "{{ postgresql_paths.config_files.environment.mode }}"
  notify: 'HANDLER | PostgreSQL restart'
  vars:
    config_items: "{{ postgresql_config_environment }}"


- name: 'CONFIG | Manage main configuration file'
  template:
    src: "{{ role_path }}/templates/etc/common.conf.j2"
    dest: "{{ postgresql_paths.config_files.main.path }}"
    owner: "{{ postgresql_paths.config_files.main.owner }}"
    group: "{{ postgresql_paths.config_files.main.group }}"
    mode: "{{ postgresql_paths.config_files.main.mode }}"
  notify: 'HANDLER | PostgreSQL restart'
  vars:
    config_items: "{{ postgresql_config_main }}"


- name: 'CONFIG | Manage pg_ctl configuration file'
  template:
    src: "{{ role_path }}/templates/etc/common.conf.j2"
    dest: "{{ postgresql_paths.config_files.pg_ctl.path }}"
    owner: "{{ postgresql_paths.config_files.pg_ctl.owner }}"
    group: "{{ postgresql_paths.config_files.pg_ctl.group }}"
    mode: "{{ postgresql_paths.config_files.pg_ctl.mode }}"
  notify: 'HANDLER | PostgreSQL restart'
  vars:
    config_items: "{{ postgresql_config_pg_ctl }}"


- name: 'CONFIG | Manage start configuration file'
  template:
    src: "{{ role_path }}/templates/etc/start.conf.j2"
    dest: "{{ postgresql_paths.config_files.start.path }}"
    owner: "{{ postgresql_paths.config_files.start.owner }}"
    group: "{{ postgresql_paths.config_files.start.group }}"
    mode: "{{ postgresql_paths.config_files.start.mode }}"
  notify: 'HANDLER | PostgreSQL restart'


- name: 'CONFIG | Manage pg_hba configuration file'
  template:
    src: "{{ role_path }}/templates/etc/pg_hba.conf.j2"
    dest: "{{ postgresql_paths.config_files.pg_hba.path }}"
    owner: "{{ postgresql_paths.config_files.pg_hba.owner }}"
    group: "{{ postgresql_paths.config_files.pg_hba.group }}"
    mode: "{{ postgresql_paths.config_files.pg_hba.mode }}"
  notify: 'HANDLER | PostgreSQL restart'


- name: 'CONFIG | Manage pg_ident configuration file'
  template:
    src: "{{ role_path }}/templates/etc/pg_ident.conf.j2"
    dest: "{{ postgresql_paths.config_files.pg_ident.path }}"
    owner: "{{ postgresql_paths.config_files.pg_ident.owner }}"
    group: "{{ postgresql_paths.config_files.pg_ident.group }}"
    mode: "{{ postgresql_paths.config_files.pg_ident.mode }}"
  notify: 'HANDLER | PostgreSQL restart'
