---

# PostgreSQL configuration files management
#------------------------------------------------------------------------------

- name: 'CONFIG | Manage main configuration file'
  template:
    src: "{{ role_path }}/templates/etc/postgresql.conf.j2"
    dest: "{{ postgresql_paths.config_file_main.path }}"
    owner: "{{ postgresql_paths.config_file_main.owner }}"
    group: "{{ postgresql_paths.config_file_main.group }}"
    mode: "{{ postgresql_paths.config_file_main.mode }}"
  notify: 'HANDLER | PostgreSQL restart'
