---

dependency:
  name: 'galaxy'
driver:
  name: 'docker'
lint:
  name: 'yamllint'
platforms:
  - name: "postgresql-docker-jessie"
    image: 'minimum2scp/systemd-jessie:latest'
    command: '/sbin/init'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
  - name: "postgresql-docker-xenial"
    image: 'solita/ubuntu-systemd:16.04'
    command: '/sbin/init'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
  - name: "postgresql-docker-trusty"
    image: 'ubuntu:trusty'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
provisioner:
  name: 'ansible'
  lint:
    name: 'ansible-lint'
  inventory:
    group_vars:
      all:
        postgresql_databases:
          - name: 'foo'
          - name: 'bar'
          - name: 'foobar'
        postgresql_databases_extensions:
          - name: 'cube'
            db: 'foo'
          - name: 'cube'
            db: 'foobar'
            state: 'absent'
        postgresql_users:
          - name: 'foo_user'
            db: 'foo'
          - name: 'bar_user'
            db: 'bar'
          - name: 'foobar_user'
            db: 'foobar'
        postgresql_privs:
          - db: 'bar'
            admin_option: True
            priv: 'ALL'
            role: 'bar_user'
            type: 'database'
    host_vars: {}
scenario:
  name: 'default'
verifier:
  name: 'testinfra'
  additional_files_or_dirs:
    - '../../tests'
  lint:
    name: 'flake8'
  options:
    sudo: True
